export const leaguesColumns = [
  { display: false, name: 'id', label: 'ID', sort: false, filter: false },
  { display: true, name: 'name', label: 'Name', sort: true, filter: true },
  {
    display: true,
    name: 'abbreviation',
    label: 'Abbreviation',
    sort: true,
    filter: true,
  },
  { display: true, name: 'type', label: 'Type', sort: true, filter: true },
  {
    display: true,
    name: 'point_system_name',
    label: 'Point System',
    sort: true,
    filter: true,
    update: false,
  },
  {
    display: false,
    name: 'point_system',
    label: 'Point System',
    sort: true,
    filter: true,
  },
  {
    display: true,
    name: 'description',
    label: 'Description',
    sort: false,
    filter: false,
  },
];
export const leagues = [
  { name: 'id', label: 'id', editable: false },
  {
    name: 'name',
    label: 'Name',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter League Name',
  },
  {
    name: 'abbreviation',
    label: 'Abbreviation',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter the Abbreviation',
  },
  {
    name: 'type',
    label: 'Type',
    editable: true,
    type: 'select',
    selectOptions: [
      { name: 'League', value: 'League' },
      { name: 'Tournament', value: 'Tournament' },
    ],
    placeholder: 'Please Select Type',
  },
  {
    name: 'point_system',
    label: 'Point System',
    editable: true,
    type: 'select',
    selectOptions: [
      { name: 'None', value: '3' },
      { name: '3 Point', value: '1' },
      { name: '10 Point (tie shutout point)', value: '4' },
      { name: '10 Point (no tie shutout point)', value: '5' },
      { name: '4 Point', value: '6' },
    ],
    placeholder: 'Please Select Type',
  },
  {
    name: 'description',
    label: 'Description',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Any Description',
  },
];
export const divisions = [
  { name: 'id', label: 'id', editable: false },
  {
    name: 'name',
    label: 'Name',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter division Name',
  },
  {
    name: 'level',
    label: 'Level',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter division Level',
  },
  {
    name: 'age',
    label: 'Age',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter division Age',
  },
  {
    name: 'gender',
    label: 'Gender',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter division Gender',
  },
  {
    name: 'description',
    label: 'Description',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Description',
  },
  {
    name: 'min_age',
    label: 'Minimum age',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Minimum Age',
  },
  {
    name: 'max_age',
    label: 'Maximum age',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Maximum Age',
  },
];
export const divisionsColumns = [
  { display: false, name: 'id', label: 'id', editable: false },
  {
    name: 'name',
    label: 'Name',
    sort: true,
    filter: true,
    type: 'string',
  },
  {
    name: 'level',
    label: 'Level',
    sort: true,
    filter: true,
    type: 'string',
  },
  {
    name: 'age',
    label: 'Age',
    sort: true,
    filter: true,
    type: 'string',
  },
  {
    name: 'gender',
    label: 'Gender',
    sort: true,
    filter: true,
    type: 'string',
  },
  {
    name: 'description',
    label: 'Description',
    sort: true,
    filter: true,
    type: 'string',
  },
  {
    name: 'min_age',
    label: 'Minimum age',
    sort: true,
    filter: true,
    type: 'string',
  },
  {
    name: 'max_age',
    label: 'Maximum age',
    sort: true,
    filter: true,
    type: 'string',
  },
];
export const divisionsLeague = [
  {
    name: 'name',
    label: 'Name',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Division Name',
  },
  {
    name: 'level',
    label: 'Level',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Level',
  },
  {
    name: 'age',
    label: 'Age',
    editable: true,
    type: 'select',
    selectOptions: [
      { value: '9', name: '9U' },
      { value: '10', name: '10U' },
      { value: '11', name: '11U' },
      { value: '12', name: '12U' },
      { value: '13', name: '13U' },
      { value: '14', name: '14U' },
      { value: '15', name: '15U' },
      { value: '16', name: '16U' },
      { value: '17', name: '17U' },
      { value: '18', name: '18U' },
      { value: '19', name: '19U' },
      { value: '18+', name: 'Over 18' },
      { value: '30+', name: 'Over 30' },
      { value: '40+', name: 'Over 40' },
      { value: '50+', name: 'Over 50' },
    ],
    placeholder: 'Please Enter Age',
  },
  {
    name: 'gender',
    label: 'Gender',
    editable: true,
    type: 'select',
    selectOptions: [
      { value: 'F', name: 'Female' },
      { value: 'M', name: 'Male' },
      { value: 'C', name: 'Co-Ed' },
      { value: 'O', name: 'Other' },
    ],
    placeholder: 'Please Enter Gender',
  },
  {
    name: 'description',
    label: 'Description',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Description',
  },
];
export const divisionLeagueColumns = [
  {
    display: true,
    name: 'year',
    label: 'Year',
    sort: true,
    filter: true,
    update: false,
  },
  {
    display: true,
    name: 'season',
    label: 'Season',
    sort: true,
    filter: true,
    update: false,
  },
  {
    display: true,
    name: 'gender',
    label: 'Gender',
    sort: true,
    filter: true,
    update: false,
  },
  {
    display: true,
    name: 'division_name',
    label: 'Division Name',
    sort: true,
    filter: true,
    update: false,
  },
  {
    display: true,
    name: 'level',
    label: 'Level',
    sort: true,
    filter: true,
    update: false,
  },
  {
    display: true,
    name: 'point_system_name',
    label: 'Point System',
    sort: true,
    filter: true,
    update: false,
  },
  // {
  //   display: true,
  //   name: 'league_name',
  //   label: 'League Name',
  //   sort: true,
  //   filter: true,
  //   update: false,
  // },
];
export const teamsColumns = [
  {
    display: false,
    postDisplay: false,
    name: 'id',
    label: 'Id',
  },
  {
    display: true,
    name: 'name',
    label: 'Name',
    sort: true,
    filter: true,
    required: true,
    type: 'text',
    placeholder: 'Enter the team name',
  },
  {
    display: true,
    name: 'gender',
    label: 'Gender',
    sort: true,
    filter: true,
    selectOptions: [
      { name: 'M', value: 'M' },
      { name: 'F', value: 'F' },
    ],
    required: true,
  },
  {
    display: true,
    name: 'contact_id',
    label: 'Contact',
    sort: true,
    filter: true,
    selectOptions: [
      { name: 'no contact', value: 0 },
      { name: 1, value: 1 },
    ],
  },
];
export const standingsColumns = [
  {
    display: true,
    name: 'team',
    label: 'Team',
    sort: true,
    filter: true,
  },
  {
    display: true,
    name: 'wins',
    label: 'W',
    sort: true,
    filter: true,
    type: 'number',
  },
  {
    display: true,
    name: 'losses',
    label: 'L',
    sort: true,
    filter: true,
    type: 'number',
  },
  {
    display: true,
    name: 'ties',
    label: 'T',
    sort: true,
    filter: true,
    type: 'number',
  },
  {
    display: true,
    name: 'points',
    label: 'Points',
    sort: true,
    filter: true,
    type: 'number',
  },
  {
    display: true,
    name: 'gf',
    label: 'GF',
    sort: true,
    filter: true,
    type: 'number',
  },
  {
    display: true,
    name: 'ga',
    label: 'GA',
    sort: true,
    filter: true,
    type: 'number',
  },
];
//display - table, postDisplay- form, sort-table, filter-table, selectOptions-form,required-form, type-input(form), placeholder-input(form)
