export const leaguesColumns = [
  {
    display: false,
    name: 'id',
    label: 'id',
    editable: false,
    sort: false,
    filter: false,
  },
  {
    display: true,
    name: 'name',
    label: 'Name',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter League Name',
    sort: true,
    filter: true,
    bold: true,
  },
  {
    display: true,
    name: 'abbreviation',
    label: 'Abbreviation',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter the Abbreviation',
    sort: true,
    filter: true,
  },
  {
    display: true,
    name: 'type',
    label: 'Type',
    editable: true,
    type: 'select',
    selectOptions: [
      { name: 'League', value: 'League' },
      { name: 'Tournament', value: 'Tournament' },
    ],
    placeholder: 'Please Select Type',
    sort: true,
    filter: true,
  },
  {
    display: false,
    name: 'point_system',
    label: 'Point System',
    editable: true,
    type: 'select',
    selectOptions: [
      { name: 'None', value: '3' },
      { name: '3 Point', value: '1' },
      { name: '10 Point (tie shutout point)', value: '4' },
      { name: '10 Point (no tie shutout point)', value: '5' },
      { name: '4 Point', value: '6' },
    ],
    placeholder: 'Please Select Point System',
    sort: true,
    filter: false,
  },
  {
    editable: false,
    display: true,
    name: 'point_system_name',
    label: 'Point System',
    sort: true,
    filter: true,
    update: false,
  },
  {
    name: 'description',
    label: 'Description',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Any Description',
    sort: false,
    filter: true,
  },
];
export const seasonsColumns = [
  {
    display: false,
    name: 'id',
    label: 'ID',
    sort: false,
    filter: false,
    editable: false,
  },
  {
    display: true,
    name: 'year',
    label: 'Year',
    sort: true,
    filter: true,
    editable: true,
    type: 'number',
    placeholder: 'Please Enter League Year',
  },
  {
    display: true,
    name: 'season',
    label: 'Season',
    sort: true,
    filter: true,
    editable: true,
    type: 'string',
    placeholder: 'Please Enter the Season',
  },
];
export const divisionsColumns = [
  { display: false, name: 'id', label: 'id', editable: false },
  {
    name: 'name',
    label: 'Name',
    sort: true,
    filter: true,
    editable: true,
    type: 'string',
    placeholder: 'Please Enter division Name',
  },
  {
    name: 'level',
    label: 'Level',
    sort: true,
    filter: true,
    editable: true,
    type: 'string',
    placeholder: 'Please Enter division Level',
  },
  {
    name: 'gender',
    label: 'Gender',
    sort: true,
    filter: true,
    editable: true,
    type: 'select',
    selectOptions: [
      { value: 'F', name: 'Female' },
      { value: 'M', name: 'Male' },
      { value: 'C', name: 'Co-Ed' },
      { value: 'O', name: 'Other' },
    ],
    placeholder: 'Please Enter division Gender',
  },
  {
    name: 'age',
    label: 'Age',
    sort: true,
    filter: true,
    editable: true,
    type: 'select',
    selectOptions: [
      { value: '9', name: '9U' },
      { value: '10', name: '10U' },
      { value: '11', name: '11U' },
      { value: '12', name: '12U' },
      { value: '13', name: '13U' },
      { value: '14', name: '14U' },
      { value: '15', name: '15U' },
      { value: '16', name: '16U' },
      { value: '17', name: '17U' },
      { value: '18', name: '18U' },
      { value: '19', name: '19U' },
      { value: '18+', name: 'Over 18' },
      { value: '30+', name: 'Over 30' },
      { value: '40+', name: 'Over 40' },
      { value: '50+', name: 'Over 50' },
    ],
    placeholder: 'Please Enter division Age',
  },

  {
    name: 'description',
    label: 'Description',
    displayNarrow: false,
    sort: true,
    filter: true,
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Description',
  },
  {
    name: 'min_age',
    label: 'Minimum age',
    sort: true,
    filter: true,
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Minimum Age',
    displayNarrow: false,
  },
  {
    name: 'max_age',
    label: 'Maximum age',
    sort: true,
    filter: true,
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Maximum Age',
    displayNarrow: false,
  },
];

export const divisionLeagueColumns = [
  {
    display: true,
    name: 'year',
    label: 'Year',
    sort: true,
    filter: true,
    update: false,
  },
  {
    display: true,
    name: 'season',
    label: 'Season',
    sort: true,
    filter: true,
    update: false,
  },
  {
    display: true,
    name: 'division_name',
    label: 'Division Name',
    sort: true,
    filter: true,
    update: false,
    editable: false,
  },
  {
    display: false,
    name: 'name',
    label: 'Name',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Division Name',
  },
  {
    display: true,
    name: 'gender',
    label: 'Gender',
    sort: true,
    filter: true,
    update: false,
  },
  {
    display: true,
    name: 'level',
    label: 'Level',
    sort: true,
    filter: true,
    update: false,
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Level',
  },
  {
    display: true,
    name: 'point_system_name',
    label: 'Point System',
    sort: true,
    filter: true,
    editable: false,
    update: false,
  },
  // {
  //   display: true,
  //   name: 'league_name',
  //   label: 'League Name',
  //   sort: true,
  //   filter: true,
  //   update: false,
  //   editable: false,
  //   displayNarrow: false,
  // },
  {
    name: 'description',
    label: 'Description',
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Description',
  },
];
export const teamsColumns = [
  {
    display: false,
    postDisplay: false,
    name: 'id',
    label: 'Id',
  },
  {
    display: true,
    name: 'name',
    label: 'Name',
    sort: true,
    filter: true,
    required: true,
    type: 'text',
    placeholder: 'Enter the team name',
  },
  {
    display: true,
    name: 'gender',
    label: 'Gender',
    sort: true,
    filter: true,
    type: 'select',
    selectOptions: [
      { name: 'M', value: 'M' },
      { name: 'F', value: 'F' },
    ],
    required: true,
  },
  {
    display: false,
    name: 'contact_id',
    label: 'Contact',
    sort: true,
    filter: true,
    type: 'select',
    selectOptions: [
      { name: 'no contact', value: '' },
      { name: 1, value: 1 },
    ],
    displayNarrow: false,
    editable: true,
  },
  {
    display: true,
    name: 'contact_name',
    label: 'Contact',
    sort: true,
    filter: true,
    type: 'select',
    selectOptions: [
      { name: 'no contact', value: '' },
      { name: 1, value: 1 },
    ],
    displayNarrow: false,
    editable: false,
  },
];
export const teamLeaguesColumns = [
  {
    display: false,
    postDisplay: false,
    name: 'id',
    label: 'Id',
  },
  {
    display: true,
    name: 'name',
    label: 'Name',
    sort: true,
    filter: true,
    required: true,
    type: 'text',
    placeholder: 'Enter the team name',
  },
  {
    display: true,
    name: 'gender',
    label: 'Gender',
    sort: true,
    filter: true,
    type: 'select',
    selectOptions: [
      { name: 'M', value: 'M' },
      { name: 'F', value: 'F' },
    ],
    required: true,
  },
  {
    display: false,
    name: 'contact_id',
    label: 'Contact',
    sort: true,
    filter: true,
    type: 'select',
    selectOptions: [
      { name: 'no contact', value: '' },
      { name: 1, value: 1 },
    ],
    displayNarrow: false,
    editable: true,
  },
  {
    display: true,
    name: 'contact_name',
    label: 'Contact',
    sort: true,
    filter: true,
    type: 'select',
    selectOptions: [
      { name: 'no contact', value: '' },
      { name: 1, value: 1 },
    ],
    displayNarrow: false,
    editable: false,
  },
];
export const gamesColumns = [
  {
    display: false,
    name: 'id',
    label: 'id',
    editable: false,
    sort: false,
    filter: false,
  },
  {
    display: false,
    postDisplay: false,
    name: 'division_id',
    editable: true,
    disabled: true,
    hidden: true,
  },
  {
    name: 'date',
    label: 'Date',
    sort: true,
    filter: true,
    editable: true,
    type: 'date',
    placeholder: 'Please Enter Date',
  },
  {
    name: 'time',
    label: 'Time',
    sort: true,
    filter: true,
    editable: true,
    type: 'time',
    placeholder: 'Please Enter Time',
  },
  {
    name: 'location',
    label: 'Location',
    sort: true,
    filter: true,
    editable: true,
    type: 'string',
    placeholder: 'Please Enter Location',
  },
  {
    name: 'home_team_name',
    label: 'Home Team',
    sort: true,
    filter: true,
    editable: false,
    type: 'string',
    placeholder: 'Please Enter Home Team',
    update: false,
  },
  {
    name: 'home_score',
    label: 'Home Score',
    sort: true,
    filter: true,
    editable: false,
    type: 'number',
    placeholder: 'Score',
    update: false,
    input: true,
    scoreDisplay: false,
  },
  {
    name: 'away_team_name',
    label: 'Away Team',
    sort: true,
    filter: true,
    editable: false,
    type: 'string',
    placeholder: 'Please Enter Away Team',
    update: false,
  },
  {
    name: 'away_score',
    label: 'Away Score',
    sort: true,
    filter: true,
    editable: false,
    type: 'number',
    placeholder: 'Score',
    update: false,
    input: true,
    scoreDisplay: false,
  },
  {
    display: false,
    name: 'home_team_id',
    label: 'Home Team Id',

    editable: true,
    placeholder: 'Please Select Team',
    update: false,
    type: 'select',
  },
  {
    display: false,
    name: 'away_team_id',
    label: 'Away Team Id',

    editable: true,
    placeholder: 'Please Select Team',
    update: false,
    type: 'select',
  },
];
export const standingsColumns = [
  {
    display: true,
    name: 'rankIsLocked',
    label: '',
    sort: false,
    filter: false,
  },
  { display: true, name: 'rank', label: 'Rank', sort: true, filter: true },
  {
    display: true,
    name: 'team_name',
    label: 'Team',
    sort: true,
    filter: true,
  },
  {
    display: true,
    name: 'games_played',
    label: 'GP',
    sort: true,
    filter: true,
    type: 'number',
  },
  {
    display: true,
    name: 'wins',
    label: 'W',
    sort: true,
    filter: true,
    type: 'number',
  },
  {
    display: true,
    name: 'losses',
    label: 'L',
    sort: true,
    filter: true,
    type: 'number',
  },
  {
    display: true,
    name: 'ties',
    label: 'T',
    sort: true,
    filter: true,
    type: 'number',
  },
  { display: true, name: 'percent', label: '%', sort: true, filter: true },
  {
    display: true,
    name: 'total_points',
    label: 'Points',
    sort: true,
    filter: true,
    type: 'number',
    bold: true,
  },
  {
    display: true,
    name: 'goals_scored_max',
    label: 'GF',
    sort: true,
    filter: true,
    type: 'number',
  },
  {
    display: true,
    name: 'goals_against_max',
    label: 'GA',
    sort: true,
    filter: true,
    type: 'number',
  },
  {
    display: true,
    name: 'goal_differential_min_max',
    label: 'G Dif',
    sort: true,
    filter: true,
    type: 'number',
  },
  {
    display: true,
    name: 'shutouts',
    label: 'SO',
    sort: true,
    filter: true,
    type: 'number',
  },
  {
    display: true,
    name: 'games_remaining',
    label: 'G Left',
    type: 'number',
    sort: true,
    filter: true,
  },
  {
    display: true,
    name: 'score',
    label: 'score',
    type: 'number',
    sort: true,
    filter: true,
  },
];
export const point_systemColumns = [
  { name: 'id', display: false },
  {
    name: 'name',
    label: 'Point System Type',
    sort: true,
    filter: true,

    required: true,
  },
];
//display - table, postDisplay- form, sort-table, filter-table, selectOptions-form,required-form, type-input(form), placeholder-input(form)
